class Win32BinaryOffsetsAndSizes:

    OFFSET_TO_PE_HEADER_OFFSET = 0x3C
    OFFSET_TO_ENTRYPOINT_RVA = 0x28
    OFFSET_TO_NUMBER_OF_SECTIONS = 0x6

    OFFSET_TO_SECTION_VIRTUAL_SIZE_WITHIN_SECTION_HEADER = 0X8
    OFFSET_TO_SECTION_VIRTUAL_ADDRESS_WITHIN_SECTION_HEADER = 0XC
    OFFSET_TO_SECTION_RAW_SIZE_WITHIN_SECTION_HEADER = 0x10
    OFFSET_TO_SECTION_RAW_ADDRESS_WITHIN_SECTION_HEADER = 0X14

    OFFSET_TO_SIZE_OF_CODE = 0x1C
    OFFSET_TO_BASE_OF_CODE_RVA = 0x2C
    OFFSET_TO_BASE_OF_DATA_RVA = 0x30
    OFFSET_TO_SECTION_ALIGNMENT = 0x38
    OFFSET_TO_FILE_ALIGNMENT = 0x3C
    OFFSET_TO_SIZE_OF_IMAGE = 0x50

    SIZE_OF_DATA_DIRECTORY_HEADER_ENTRY = 0x8
    DATA_DIRECTORIES_HEADER_SIZE = 0x10

    OFFSET_TO_IMPORT_TABLE_RVA = 0x80
    OFFSET_TO_IMPORT_TABLE_SIZE = 0x84
    OFFSET_TO_RESOURCE_TABLE_RVA = 0x88
    OFFSET_TO_BEGINNING_OF_SECTION_HEADERS = 0xF8

    SECTION_HEADER_SIZE = 0x28

    #Resource headers
    OFFSET_TO_NUMBER_OF_ID_ENTRIES_WITHIN_RESOURCE_DIRECTORY_HEADER = 0xE
    OFFSET_TO_OFFSET_TO_DATA_ENTRY_WITHIN_LANGUAGE = 0x14

    #Import headers
    NUMBER_OF_DWORDS_WITHIN_EACH_DIRECTORY_TABLE_ENTRY = 0x5
    NUMBER_OF_BYTES_PER_IMPORT_DIRECTORY_TABLE_ENTRY = 0x14
    OFFSET_TO_IMPORT_NAME_TABLE_RVA_WITHIN_IMPORT_DIRECTORY_TABLE = 0x0
    OFFSET_TO_NAME_RVA_WITHIN_IMPORT_DIRECTORY_TABLE = 0xC
    OFFSET_TO_IMPORT_ADDRESS_TABLE_RVA_WITHIN_IMPORT_DIRECTORY_TABLE = 0x10
